name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  apply:
    name: Terraform Apply
    runs-on: vollminlab

    steps:
      - uses: actions/checkout@v4

      - uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: op://Homelab/Github-Org-PAT/password
          TF_TOKEN_app_terraform_io: op://Homelab/Terraform-Cloud-Token/credential

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="github_token=$GITHUB_TOKEN"
